# Generated by Django 5.2.10 on 2026-01-25 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_appointmentdetails_id_alter_customeuser_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('staff', 'staff')], default='customer', max_length=20),
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.department'),
        ),
    ]
