# Generated by Django 5.2.10 on 2026-01-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_customeuser_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('staff', 'Staff')], default='customer', max_length=20),
        ),
    ]
