# Generated by Django 5.2.10 on 2026-01-25 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_customeuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetails',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.department'),
        ),
    ]
