# Generated by Django 5.2.10 on 2026-01-25 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_profiledetails_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheduledetails',
            name='admin',
            field=models.ForeignKey(limit_choices_to={'role': 'staff'}, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL),
        ),
    ]
