# Generated by Django 5.2.10 on 2026-01-25 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_sheduledetails_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentdetails',
            name='user',
        ),
        migrations.AddField(
            model_name='appointmentdetails',
            name='customer',
            field=models.ForeignKey(default=1, limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='user_appointments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointmentdetails',
            name='admin',
            field=models.ForeignKey(limit_choices_to={'role': 'staff'}, on_delete=django.db.models.deletion.CASCADE, related_name='admin_appointments', to=settings.AUTH_USER_MODEL),
        ),
    ]
