# Generated by Django 5.2.10 on 2026-01-25 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_remove_appointmentdetails_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentdetails',
            name='customer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'customer'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_appointments', to=settings.AUTH_USER_MODEL),
        ),
    ]
