# Generated by Django 5.2.10 on 2026-02-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_rename_name_department_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('doctor', 'Doctor'), ('staff', 'Staff')], default='customer', max_length=20),
        ),
    ]
