# Generated by Django 5.2.10 on 2026-02-08 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_customeuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentdetails',
            name='admin',
            field=models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='admin_appointments', to=settings.AUTH_USER_MODEL),
        ),
    ]
